services:
  saloony-front:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: saloony-front
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - HOSTNAME=0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - saloony

networks:
  saloony:
    driver: bridge
