name: Develop workflow

on:
  push:
    branches:
      - develop
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6-beta
      - name: List repository files
        run: ls -la
